config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks", registrations: "registrations" }

  root "posts#index"

  resources :posts

  get "/search", to: "home#search", as: "search"
  get "/check_new_posts", to: "home#check_new_posts", as: "check_new_posts"

  post "/users/:id/track", to: "home#track_user", as: "track_frequency"
  get "/users/:id", to: "home#profile", as: "users"

  post "/personal", to: "home#personal"

end

app/models/notifiable.rb
module Notifiable

  def notify(args = {})
    user = args[:user]
    return unless user
    family = args[:family] || "none"
    user.notifications.create(notified_by: self, family: family, dismissed: false)
  end
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  belongs_to :notified_by, class_name: "User", foreign_key: "notified_by"
end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :user
  validates :body, presence: true
  validates :user, presence: true

end

app/models/tracking.rb
class Tracking < ActiveRecord::Base
  
  belongs_to :user
  belongs_to :frequency, class_name: "User"

end

app/models/user.rb
class User < ActiveRecord::Base
  include Notifiable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  
  # make the tracking and infer tracked_by with a where clause
  has_many :trackings
  has_many :frequencies, through: :trackings
  has_many :notifications

  validates :name, presence: true, length: { in: 1..200 }

  def top_notifications
    notifications.order(created_at: "desc").limit(5)
  end

  def notify?
    top_notifications.any? { |n| n.dismissed == false }
  end

  def dismiss_notification(notification_id)
    notification = notifications.find(notification_id)
    if notification
      notification.update(dismissed: true, dismissed_at: DateTime.now)
    end
  end

  def track_user(user)
    if tracking = trackings.create(frequency: user) 
      notify(user: user, family: "tracking")
    end
  end

  def tracked_by
   Tracking.where(frequency_id: self.id)
  end
  
  def tracking?(user)
    trackings.where(frequency_id: user.id).size > 0
  end

  # fetches his/er own posts and the posts of users whose frequency s/he is tracking
  def timeline_posts
    ids = self.trackings.collect(&:frequency_id)
    ids << self.id
    Post.where("user_id IN (#{ids.join(',')})").order(created_at: "desc")
  end

  # used for displaying on views
  def to_s
    email
  end

  def self.find_or_create_from_oauth(oauth_env)
    User.where(email: oauth_env["info"]["email"]).first_or_create do |user|
      user.name = oauth_env["info"]["name"]
      user.email = oauth_env["info"]["email"]
      user.password = Devise.friendly_token
    end
  end

  def self.search(term)
    where("email ILIKE ?", "%#{term}%")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def search
    # params[:q] seems very insecure
    @search_term = params[:q]
    @users = User.search(params[:q]).to_a
  end

  def check_new_posts
    posts_count = current_user.timeline_posts.count
    # sanitize session input
    current_posts_count = Integer(session[:posts_count]) or current_posts_count = 0
    render json: { "new_posts": (posts_count - current_posts_count) }
  end

  def profile
    @user = User.find(params[:id])
  end

  def personal
    dimsissal = current_user.dismiss_notification(params[:notif_id])
    render nothing: true
  end

  def track_user
    current_user.track_user(User.find(params[:id]))
  end

end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.find_or_create_from_oauth(request.env["omniauth.auth"])
    flash[:notice] = "Hi, #{@user.email}!"
    sign_in_and_redirect @user
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @post = current_user.posts.build
    @posts = current_user.timeline_posts.page params[:page]
    session[:posts_count] = @posts.size
  end

  def new
    @post = current_user.posts.build
  end

  def create
    post = current_user.posts.build(post_params)
    if post.save
      redirect_to post, notice: "Your new message is hot off the ...oven." 
    else
      redirect_to posts_path
    end
  end

  def show
    @post = current_user.posts.find(params[:id])
  end

  private

  def post_params
    params.require(:post).permit(:body)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :remember_me)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/trackings_controller.rb
class TrackingsController < ApplicationController

  def create
    current_user.track_user(User.find(params[:id]))

    respond_to do |format|
      format.js
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  #def flash_message
  #  messages = ""
  #  [:notice, :info, :warning, :error].each {|type|
  #    if flash[type]
  #      messages += "<p class=\"#{type}\">#{flash[type]}</p>"
  #    end
  #  }

  #  messages
  #end

  def current_user_in(users)
    users == users.reject! { |user| user == current_user }
  end

end

app/views/home/index.html.erb
<div class="wave-slider">
  <div class="wave">
    <div class="wave-content"></div>
    <div class="wave-user-info">
      <img class="wave-user-profile-pic" src="" />
      <span class="wave-user-name"></>
    </div>
  </div>
</div>

app/views/home/profile.html.erb
<span class="profile-title"><%= @user.name %></span>

<% if current_user.tracking? @user %>
  <%= link_to I18n.t("user.tracker.untrack"), track_frequency_path(@user), id: "track_frequency", method: :post, remote: true %>
<% else %>
  <%= link_to I18n.t("user.tracker.track"), track_frequency_path(@user), id: "track_frequency", method: :post, remote: true %>
<% end %>

<hr class="hr-clear">

<ul class="list-group">
  <li class="list-group-item">member since <%= @user.created_at.strftime("%d %B %Y") %></li>
</ul>

<h2><%= "#{@user.name}'s latest posts" %></h2>

<%= render @user.posts %>

app/views/home/search.html.erb
<h1>user info</h1>

<% if @users %>
  <h3>search results for <%= @search_term %></h3>
  <table class="table">
    <thead>
      <th>email</th>
      <th>user since</th>
    </thead>
    <tbody>
    <% if current_user_in @users %>
      <tr class="search_self">
        <td><%= link_to current_user.email, users_path(current_user) %></td>
        <td><%= current_user.created_at %></td>
      </tr>
    <% end %>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.email, users_path(user) %></td>
        <td><%= user.created_at %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <h3>no user found =[</h3>
<% end %>

app/views/home/track_user.js.erb
$("#track_frequency").html("forget this frequency")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<title><%= "(!) " if current_user.try(:notify?) %> microwave</title>
<link href='https://fonts.googleapis.com/css?family=Josefin+Sans' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
<%= stylesheet_link_tag    'animate', media: 'all' %>
<%= stylesheet_link_tag    'application', media: 'all' %>

<%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">microwave</a>
    </div>
    <div id="navbar" class="collapse pull-right navbar-collapse">
      <% if current_user %>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown notification">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %><span class="caret"></span></a>
          <div class="notification-dot <%= current_user.notify? ? 'notification-display' : 'no-notifications' %>"></div>
          <ul class="dropdown-menu">
            <% current_user.top_notifications.each do |notification| %>
              <div class="notification-box" data-notif="<%= notification.id %>">
                <li><span id="notified_by"><%= notification.notified_by %></span></li>
                <li><span id="notified_at"><%= time_ago_in_words notification.created_at %> ago</span></li>
                <li><span id="notification_message"><%= notification.message %></span></li>
              </div>
              <li role="separator" class="divider"></li>
            <% end %>
            <li><%= link_to "logout", destroy_user_session_path, method: 'delete' %></li>
          </ul>
          </li>
          <li>
          <form action="/search">
            <input id="search_bar" class="search-invisible"placeholder="Search for users" name="q" type="text" />
            <%= submit_tag "search", id: "search", class: "search-invisible" %>
            <i id="search_glass" class="fa fa-search"></i>
          </form>
            </li>
          <% end %>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </nav>


  <div class="container">

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </div>

  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag controller_name if Rails.application.assets.find_asset("#{controller_name}.js") %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

  </body>
  </html>

app/views/posts/_form.html.erb
<div class="row">
  <div class="col-md-push-2 col-md-6">
    <%= simple_form_for(@post, remote: true) do |f| %>
      <%= f.input :body, as: :string, label: false %>
      <%= f.submit "Microwave it!" %>
    <% end %>
  </div>
</div>

app/views/posts/_post.html.erb
<div class="row">
  <div class="col-md-push-2 col-md-6">
    <div class="post-item wow fadeInRight">
      <p class="post-user"><%= post.user.name %></p>
      <p class="post-body"><%= truncate(strip_tags(post.body), length: 400) %></p>
      <p class="post-time"><%= time_ago_in_words(post.created_at) %> ago</p>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<%= render 'form' %>

<div class="row">
  <div class="col-md-push-2 col-md-6">
    <div id="new_posts" class="fadeIn">
      <a href="/" id="load_new_posts"></a>
    </div>
  </div>
</div>

<div id="waves">
  <%= render @posts %>
</div>

<div id="scrollin">
  <%= paginate @posts %>
</div>

app/views/posts/index.js.erb
$("#waves").append('<%= j render @posts %>');
<% if @posts.next_page %>
  $("#scrollin").html('<%= j paginate @posts %>');
<% else %>
  $("#scrollin").remove();
<% end %>

app/views/posts/new.html.erb
<h1>your posts</h1>

<%= render 'form' %>

<%= link_to 'cancel', '#' %>

app/views/posts/show.html.erb
<h1>post details</h1>

<p>Message</p>

<%= @post.body %>

app/views/posts/show.js.erb
window.location.reload(true);